services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"
            
    KimaiPlugin\EasyBackupBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/'
            - '../../Tests'
            - '../../vendor'

    KimaiPlugin\EasyBackupBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    KimaiPlugin\EasyBackupBundle\Command\EasyBackupBackupCommand:
        tags: ['console.command']
